include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    prefer_const_constructors: ignore
    library_private_types_in_public_api: ignore
    use_super_parameters: ignore
    prefer_const_literals_to_create_immutables: ignore
    non_constant_identifier_names: ignore
    no_wildcard_variable_uses: ignore
