name: inthon_front
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.6.0

  google_fonts: ^6.2.1
  go_router: ^14.3.0
  intl: ^0.19.0
  get: ^4.6.6
  flutter_secure_storage: ^9.2.2
  dio: ^5.7.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  freezed_annotation: ^2.4.4
  url_launcher: ^6.3.1

  ## UI ##
  sprung: ^3.0.1
  dropdown_button2: ^2.3.9
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  shadcn_ui: ^0.15.1
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  loading_animation_widget: ^1.2.0+4
  flutter_sliding_tutorial: ^2.0.0+1
  page_transition: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.2
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/
