// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD1j-4ZatPeVyh7BT8ntLEptDOAqublPQ',
    appId: '1:1067111695591:web:4b2807a31dbcd0db114e42',
    messagingSenderId: '1067111695591',
    projectId: 'inthon-leaf',
    authDomain: 'inthon-leaf.firebaseapp.com',
    storageBucket: 'inthon-leaf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBFQxEb9s_KuxBPUDJywmYNJiVIWRwj0k',
    appId: '1:1067111695591:android:95808b25cadb7bd7114e42',
    messagingSenderId: '1067111695591',
    projectId: 'inthon-leaf',
    storageBucket: 'inthon-leaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDifjhmjfRE6O4q8YHvuwGs2qSkBV80j9Y',
    appId: '1:1067111695591:ios:d555f333e180e6c1114e42',
    messagingSenderId: '1067111695591',
    projectId: 'inthon-leaf',
    storageBucket: 'inthon-leaf.firebasestorage.app',
    iosBundleId: 'com.example.inthonFront',
  );
}
